-- Schéma Trigger Météo Wellpack
-- À exécuter sur une base vide wellpack_trigger_meteo


-- Table: public.stores

-- DROP TABLE IF EXISTS public.stores;

CREATE TABLE IF NOT EXISTS public.stores
(
    id integer NOT NULL,
    label text COLLATE pg_catalog."default",
    store_name text COLLATE pg_catalog."default" NOT NULL,
    postal_code text COLLATE pg_catalog."default" NOT NULL,
    contact_email text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT stores_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.stores
    OWNER to postgres;


-- Table: public.runs

-- DROP TABLE IF EXISTS public.runs;

CREATE TABLE IF NOT EXISTS public.runs
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    store_id integer,
    ran_at timestamp with time zone DEFAULT now(),
    conditions_ok boolean,
    emails_sent integer DEFAULT 0,
    issues text COLLATE pg_catalog."default",
    details jsonb,
    CONSTRAINT runs_pkey PRIMARY KEY (id),
    CONSTRAINT store_id FOREIGN KEY (store_id)
        REFERENCES public.stores (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.runs
    OWNER to wellpack_user;


-- Table: public.store_conditions

-- DROP TABLE IF EXISTS public.store_conditions;

CREATE TABLE IF NOT EXISTS public.store_conditions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    store_id integer NOT NULL,
    temp_min numeric,
    temp_max numeric,
    precip_min numeric,
    precip_max numeric,
    wind_min numeric,
    wind_max numeric,
    uv_min numeric,
    raw_conditions jsonb,
    CONSTRAINT store_conditions_pkey PRIMARY KEY (id),
    CONSTRAINT store_id FOREIGN KEY (store_id)
        REFERENCES public.stores (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.store_conditions
    OWNER to wellpack_user;


-- Table: public.store_windows

-- DROP TABLE IF EXISTS public.store_windows;

CREATE TABLE IF NOT EXISTS public.store_windows
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    store_id integer NOT NULL,
    days_past integer,
    days_future integer,
    state boolean NOT NULL DEFAULT false,
    last_run timestamp with time zone,
    last_input jsonb,
    repeat_hours integer NOT NULL DEFAULT 24,
    CONSTRAINT store_windows_pkey PRIMARY KEY (id),
    CONSTRAINT store_id FOREIGN KEY (store_id)
        REFERENCES public.stores (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.store_windows
    OWNER to wellpack_user;


